/*
-- Query: SELECT * FROM airline.country
-- Date: 2019-06-03 22:39
*/
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (1,'﻿Kosovo','XK','XKS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (2,'Svalbard','XR','XSV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (3,'West Bank','XW','XWB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (4,'Yemen','YE','YEM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (5,'Mayotte','YT','MYT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (6,'South Africa','ZA','ZAF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (7,'Zambia','ZM','ZMB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (8,'Zimbabwe','ZW','ZWE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (9,'Kazakhstan','KZ','KAZ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (10,'Laos','LA','LAO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (11,'Lebanon','LB','LBN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (12,'Saint Lucia','LC','LCA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (13,'Liechtenstein','LI','LIE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (14,'Sri Lanka','LK','LKA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (15,'Liberia','LR','LBR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (16,'Lesotho','LS','LSO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (17,'Lithuania','LT','LTU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (18,'Luxembourg','LU','LUX');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (19,'Latvia','LV','LVA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (20,'Libya','LY','LBY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (21,'Morocco','MA','MAR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (22,'Monaco','MC','MCO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (23,'Moldova','MD','MDA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (24,'Montenegro','ME','MNE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (25,'Saint Martin','MF','MAF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (26,'Madagascar','MG','MDG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (27,'Marshall Islands','MH','MHL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (28,'Macedonia','MK','MKD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (29,'Mali','ML','MLI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (30,'Burma','MM','MMR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (31,'Mongolia','MN','MNG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (32,'Macau','MO','MAC');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (33,'Martinique','MQ','MTQ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (34,'Mauritania','MR','MRT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (35,'Montserrat','MS','MSR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (36,'Malta','MT','MLT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (37,'Mauritius','MU','MUS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (38,'Maldives','MV','MDV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (39,'Malawi','MW','MWI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (40,'Mexico','MX','MEX');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (41,'Malaysia','MY','MYS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (42,'Mozambique','MZ','MOZ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (43,'Namibia','NA','NAM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (44,'New Caledonia','NC','NCL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (45,'Niger','NE','NER');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (46,'Norfolk Island','NF','NFK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (47,'Nigeria','NG','NGA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (48,'Nicaragua','NI','NIC');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (49,'Netherlands','NL','NLD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (50,'Norway','NO','NOR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (51,'Nepal','NP','NPL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (52,'Niue','NU','NIU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (53,'New Zealand','NZ','NZL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (54,'Oman','OM','OMN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (55,'Panama','PA','PAN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (56,'Peru','PE','PER');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (57,'French Polynesia','PF','PYF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (58,'Papua New Guinea','PG','PNG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (59,'Philippines','PH','PHL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (60,'Pakistan','PK','PAK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (61,'Poland','PL','POL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (62,'Saint Pierre And Miquelon','PM','SPM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (63,'Pitcairn Islands','PN','PCN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (64,'Portugal','PT','PRT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (65,'Palau','PW','PLW');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (66,'Paraguay','PY','PRY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (67,'Qatar','QA','QAT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (68,'Reunion','RE','REU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (69,'Romania','RO','ROU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (70,'Serbia','RS','SRB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (71,'Russia','RU','RUS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (72,'Rwanda','RW','RWA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (73,'Saudi Arabia','SA','SAU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (74,'Solomon Islands','SB','SLB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (75,'Seychelles','SC','SYC');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (76,'Sudan','SD','SDN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (77,'Sweden','SE','SWE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (78,'Singapore','SG','SGP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (79,'Saint Helena. Ascension. And Tristan Da Cunha','SH','SHN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (80,'Slovenia','SI','SVN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (81,'Slovakia','SK','SVK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (82,'Sierra Leone','SL','SLE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (83,'San Marino','SM','SMR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (84,'Senegal','SN','SEN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (85,'Somalia','SO','SOM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (86,'Suriname','SR','SUR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (87,'South Sudan','SS','SSD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (88,'Sao Tome And Principe','ST','STP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (89,'El Salvador','SV','SLV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (90,'Sint Maarten','SX','SXM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (91,'Syria','SY','SYR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (92,'Swaziland','SZ','SWZ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (93,'Turks And Caicos Islands','TC','TCA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (94,'Chad','TD','TCD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (95,'Togo','TG','TGO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (96,'Thailand','TH','THA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (97,'Tajikistan','TJ','TJK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (98,'Timor-Leste','TL','TLS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (99,'Turkmenistan','TM','TKM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (100,'Tunisia','TN','TUN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (101,'Tonga','TO','TON');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (102,'Turkey','TR','TUR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (103,'Trinidad And Tobago','TT','TTO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (104,'Tuvalu','TV','TUV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (105,'Taiwan','TW','TWN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (106,'Tanzania','TZ','TZA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (107,'Ukraine','UA','UKR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (108,'Uganda','UG','UGA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (109,'Uruguay','UY','URY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (110,'Uzbekistan','UZ','UZB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (111,'Saint Vincent And The Grenadines','VC','VCT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (112,'Venezuela','VE','VEN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (113,'Virgin Islands. British','VG','VGB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (114,'Vietnam','VN','VNM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (115,'Vanuatu','VU','VUT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (116,'Wallis And Futuna','WF','WLF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (117,'Samoa','WS','WSM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (118,'Andorra','AD','AND');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (119,'United Arab Emirates','AE','ARE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (120,'Afghanistan','AF','AFG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (121,'Antigua And Barbuda','AG','ATG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (122,'Anguilla','AI','AIA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (123,'Albania','AL','ALB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (124,'Armenia','AM','ARM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (125,'Angola','AO','AGO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (126,'Argentina','AR','ARG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (127,'Austria','AT','AUT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (128,'Australia','AU','AUS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (129,'Aruba','AW','ABW');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (130,'Azerbaijan','AZ','AZE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (131,'Bosnia And Herzegovina','BA','BIH');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (132,'Barbados','BB','BRB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (133,'Bangladesh','BD','BGD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (134,'Belgium','BE','BEL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (135,'Burkina Faso','BF','BFA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (136,'Bulgaria','BG','BGR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (137,'Bahrain','BH','BHR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (138,'Burundi','BI','BDI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (139,'Benin','BJ','BEN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (140,'Saint Barthelemy','BL','BLM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (141,'Bermuda','BM','BMU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (142,'Brunei','BN','BRN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (143,'Bolivia','BO','BOL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (144,'Brazil','BR','BRA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (145,'Bahamas. The','BS','BHS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (146,'Bhutan','BT','BTN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (147,'Botswana','BW','BWA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (148,'Belarus','BY','BLR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (149,'Belize','BZ','BLZ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (150,'Canada','CA','CAN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (151,'Congo (Kinshasa)','CD','COD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (152,'Central African Republic','CF','CAF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (153,'Congo (Brazzaville)','CG','COG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (154,'Switzerland','CH','CHE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (155,'Côte D’Ivoire','CI','CIV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (156,'Cook Islands','CK','COK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (157,'Chile','CL','CHL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (158,'Cameroon','CM','CMR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (159,'China','CN','CHN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (160,'Colombia','CO','COL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (161,'Costa Rica','CR','CRI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (162,'Cuba','CU','CUB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (163,'Cabo Verde','CV','CPV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (164,'Curaçao','CW','CUW');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (165,'Christmas Island','CX','CXR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (166,'Cyprus','CY','CYP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (167,'Czechia','CZ','CZE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (168,'Germany','DE','DEU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (169,'Djibouti','DJ','DJI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (170,'Denmark','DK','DNK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (171,'Dominica','DM','DMA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (172,'Dominican Republic','DO','DOM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (173,'Algeria','DZ','DZA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (174,'Ecuador','EC','ECU');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (175,'Estonia','EE','EST');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (176,'Egypt','EG','EGY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (177,'Eritrea','ER','ERI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (178,'Spain','ES','ESP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (179,'Ethiopia','ET','ETH');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (180,'Finland','FI','FIN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (181,'Fiji','FJ','FJI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (182,'Falkland Islands (Islas Malvinas)','FK','FLK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (183,'Micronesia. Federated States Of','FM','FSM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (184,'Faroe Islands','FO','FRO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (185,'France','FR','FRA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (186,'Gabon','GA','GAB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (187,'United Kingdom','GB','GBR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (188,'Grenada','GD','GRD');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (189,'Georgia','GE','GEO');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (190,'French Guiana','GF','GUF');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (191,'Guernsey','GG','GGY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (192,'Ghana','GH','GHA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (193,'Gibraltar','GI','GIB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (194,'Greenland','GL','GRL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (195,'Gambia. The','GM','GMB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (196,'Guinea','GN','GIN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (197,'Guadeloupe','GP','GLP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (198,'Equatorial Guinea','GQ','GNQ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (199,'Greece','GR','GRC');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (200,'South Georgia And South Sandwich Islands','GS','SGS');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (201,'Guatemala','GT','GTM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (202,'Guinea-Bissau','GW','GNB');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (203,'Guyana','GY','GUY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (204,'Hong Kong','HK','HKG');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (205,'Honduras','HN','HND');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (206,'Croatia','HR','HRV');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (207,'Haiti','HT','HTI');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (208,'Hungary','HU','HUN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (209,'Indonesia','ID','IDN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (210,'Ireland','IE','IRL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (211,'Israel','IL','ISR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (212,'Isle Of Man','IM','IMN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (213,'India','IN','IND');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (214,'Iraq','IQ','IRQ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (215,'Iran','IR','IRN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (216,'Iceland','IS','ISL');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (217,'Italy','IT','ITA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (218,'Jersey','JE','JEY');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (219,'Jamaica','JM','JAM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (220,'Jordan','JO','JOR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (221,'Japan','JP','JPN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (222,'Kenya','KE','KEN');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (223,'Kyrgyzstan','KG','KGZ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (224,'Cambodia','KH','KHM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (225,'Kiribati','KI','KIR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (226,'Comoros','KM','COM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (227,'Saint Kitts And Nevis','KN','KNA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (228,'North Korea','KP','PRK');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (229,'South Korea','KR','KOR');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (230,'Kuwait','KW','KWT');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (231,'Cayman Islands','KY','CYM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (232,'American Samoa','AS','ASM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (233,'Guam','GU','GUM');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (234,'Northern Mariana Islands','MP','MNP');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (235,'United States','US','USA');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (236,'Palestine','PS','PSE');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (296,'British Indian Ocean Territory',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (297,'Antarctica',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (298,'Midway Islands',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (299,'Virgin Islands',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (300,'Puerto Rico',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (301,'Netherlands Antilles',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (302,'Nauru',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (303,'Johnston Atoll',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (304,'Western Sahara',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (305,'Cocos (Keeling) Islands',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (306,'Myanmar',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (307,'Wake Island',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (308,'Offshore islands',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (309,'Sint measle',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (310,'Sao Toma',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (311,'Contao islands',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (312,'Contao mainland',' ',' ');
INSERT INTO `` (`idCountry`,`CountryName`,`ISO2`,`ISO3`) VALUES (313,'Turks islands',' ',' ');
